import AppKit
import Foundation

/// Polls `NSPasteboard.general.changeCount` on a timer and reports new clips.
/// Polling is the standard approach here — there is no change notification for
/// the pasteboard, and a 0.5s tick is cheap (an integer compare per tick).
final class ClipboardWatcher {
    /// Pasteboard types that mean "don't record this" by community convention.
    /// Password managers mark their clips concealed; utilities mark scratch
    /// content transient. Honouring these keeps secrets out of the history file.
    private static let excludedTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    private let pasteboard = NSPasteboard.general
    private var timer: Timer?

    /// Our own paste writes are intentionally *not* filtered out: re-pasting an
    /// old clip makes it the current clipboard content, and letting it flow back
    /// through here moves it to the top of the history for free.
    private var lastChangeCount: Int

    var onNewClip: ((ClipItem) -> Void)?

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start(interval: TimeInterval = 0.5) {
        stop()
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        // .common so the poll keeps running while a menu is open or a window is
        // being dragged; the default mode stalls during those tracking loops.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        guard let item = readCurrentClip() else { return }
        onNewClip?(item)
    }

    private func readCurrentClip() -> ClipItem? {
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.excludedTypes) else { return nil }

        // Prefer text: a rich-text copy carries string + html + rtf together,
        // and the plain string is what we want to show and paste.
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return ClipItem(text: string)
        }

        if let png = pasteboard.data(forType: .png) {
            return ClipItem(imageData: png)
        }

        // Screenshots and many apps put TIFF on the board; normalize to PNG so
        // storage is one format.
        if let tiff = pasteboard.data(forType: .tiff),
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            return ClipItem(imageData: png)
        }

        return nil
    }
}
